### ISSUE TITLE
IndexError: single positional indexer is out-of-bounds while parsing runinfo file

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/rnaseq-pipeline#75]
```
Runtime error:
Traceback (most recent call last):
  File "/home/rogic/miniconda3/envs/rnaseq-pipeline/lib/python3.7/site-packages/luigi/worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "/home/rogic/miniconda3/envs/rnaseq-pipeline/lib/python3.7/site-packages/luigi/worker.py", line 142, in _run_get_new_deps
    requires = next(task_gen)
  File "/home/rogic/miniconda3/envs/rnaseq-pipeline/lib/python3.7/site-packages/rnaseq_pipeline/sources/sra.py", line 145, in run
    run = df.sort_values('Run', ascending=False).iloc[0]
  File "/home/rogic/miniconda3/envs/rnaseq-pipeline/lib/python3.7/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/rogic/miniconda3/envs/rnaseq-pipeline/lib/python3.7/site-packages/pandas/core/indexing.py", line 1566, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/rogic/miniconda3/envs/rnaseq-pipeline/lib/python3.7/site-packages/pandas/core/indexing.py", line 1500, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

**Comment by arteymix** [comment]
Fixed in 98ac2bd19375a7af8a6efa2b27f350e529350ba2, the runinfo file was empty
